import type { Metadata } from "next";
import SimpleHeader from "app/components/simpleHeader";
import Providers from "app/providers";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SimpleHeader />
      <Providers>{children}</Providers>
    </>
  );
}
